name: accessto
channels:
  - conda-forge

# I had some issues running OGR directly from a command line with 
# the default r5py installation. Trying to resolve this by constraining
# the versions. Test later on to see if we can remove specifying 
# fiona and pyogrio in this file to use the one coming directly from r5py.
dependencies:
  - python=3.11
  - pyogrio=0.7.*
  - fiona=1.9.*
  - r5py=0.1.1
  - jupyterlab
  - yaml

